[package]
name = "coven"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
log4rs = "1.2.0"
async-log = "2.0.0"
tracing = "0.1.40"

[lib]
crate-type = ["lib"]
